#!/bin/bash

G="\033[0;32m";
Y="\033[0;33m";
R="\033[0;31m";
NC="\033[0m";

# Invalid maps tester
MAPS_FOLDER=./tests/invalid/;
MAPS=$(ls "$MAPS_FOLDER");
echo "[INVALID MAPS]";
for MAP in $MAPS; do
	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
	if [[ $? == 0 ]]; then
		echo -en "${R}[FAIL]${NC}"
	else
		echo -en "${G}[OK]${NC}";
	fi;
	echo "[$MAP]"
done;


# Valid maps tester
MAPS_FOLDER=./tests/valid/;
MAPS=$(ls "$MAPS_FOLDER");
echo -e "\n[VALID MAPS]";
for MAP in $MAPS; do
	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
	if [[ $? == 0 ]]; then
		echo -en "${G}[OK]${NC}";
	else
		echo -en "${R}[FAIL]${NC}"
	fi;
	echo "[$MAP]"
done;
